// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace NEOSxGUI
{
    public partial class noScrollView : NSScrollView
	{
        public noScrollView (IntPtr handle) : base (handle)
		{
		}
        public override void ScrollWheel(NSEvent theEvent)
        {
            
        }

	}
}
