// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace NEOSxGUI
{
	public partial class SettingsVC : NSView
	{
		public SettingsVC (IntPtr handle) : base (handle)
		{
		}
	}
}
