// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using Neo.Implementations.Wallets.NEP6;
using Neo.Wallets;
using System.Threading.Tasks;
namespace NEOSxGUI
{
    public partial class WalletVC : NSView
    {
        public WalletVC(IntPtr handle) : base(handle)
        {
        }
        public override void ViewDidMoveToSuperview()
        {
            base.ViewDidMoveToSuperview();
            table.DataSource = DataSource;
            table.Delegate = new AddressTableDelegate(this, DataSource);
            table.ReloadData();
        }

        public void update(){
            table.ReloadData();
            var init_int = DataSource.addresses.Count;
            for (int i = 0; i < init_int; i++)
            {
                var a = DataSource.addresses[i];
                if (a.top == true){
                    DataSource.addresses.Remove(DataSource.addresses[i]);
                    DataSource.addresses.Insert(0, a);
                }
            }
            table.ReloadData();
            foreach (AddressTable a in DataSource.addresses)
            {
                a.top = false;
            }
        }







        partial void walletOpen(NSObject sender)
        {
            //start loading bar

            var t = Task.Run(() =>
            {
                NEP6Wallet w = new NEP6Wallet("testnet.json");
                w.Unlock("qwerasdfqwer");
                return w;

            });
            t.ContinueWith((w) => {
                var v = w.Result.GetAccounts();

                //current wallet is w
                //setup ui with w address
                //stop loading bar
                //close poopup
                BeginInvokeOnMainThread(() =>
                {
                    foreach (WalletAccount s in v)
                    {
                        DataSource.addresses.Add(new AddressTable(s.Address));
                    }
                    table.ReloadData();
                });
            }
            );

        }



        private bool extended = false;
        private AddressTableDataSource DataSource = new AddressTableDataSource();
        partial void button(NSObject sender)
        {
            table.ReloadData();

            if (extended)

            {
                
                
                scroll.SetFrameSize(new CoreGraphics.CGSize(scroll.Frame.Width, scroll.Frame.Height - 180));
                scroll.SetFrameOrigin(new CoreGraphics.CGPoint(scroll.Frame.X, scroll.Frame.Y + 180));
            }
            else
            {
                scroll.SetFrameSize(new CoreGraphics.CGSize(scroll.Frame.Width, scroll.Frame.Height + 180));
                scroll.SetFrameOrigin(new CoreGraphics.CGPoint(scroll.Frame.X, scroll.Frame.Y - 180));
            }
            extended = !extended;
            foreach (AddressTable a in DataSource.addresses)
            {
                a.extended = !a.extended;
            }
        }


    }
}
