// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace NEOSxGUI
{
	public partial class WalletVC : NSView
	{
		public WalletVC (IntPtr handle) : base (handle)
		{
		}
	}
}
