// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace NEOSxGUI
{
	public partial class windowController : NSWindowController
	{
		public windowController (IntPtr handle) : base (handle)
		{
            
		}



    }
}
